import { chromium } from 'playwright-core';
const out = process.argv[2]; const cls = process.argv[3] || 'ranger';
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome', args: ['--use-gl=angle', '--use-angle=swiftshader', '--enable-unsafe-swiftshader', '--ignore-gpu-blocklist', '--no-sandbox', '--disable-dev-shm-usage'] });
const p = await b.newPage({ viewport: { width: 462, height: 783 }, hasTouch: true });
const problems = []; p.on('pageerror', (e) => problems.push(e.message));
await p.addInitScript(() => { try { localStorage.setItem('qd.tutorial.done', '1'); localStorage.setItem('qd.hints', 'off'); } catch {} });
await p.goto('http://localhost:8135/?debug&manual&q=low'); await p.waitForFunction(() => window.QD?.world?.stage, null, { timeout: 90000 });
const pump = (s) => p.evaluate(async (s) => { const st = window.QD.world.stage; const n = Math.max(1, Math.round(s * 15)); for (let i = 0; i < n; i++) { st.simulate(1 / 15, 1 / 30); await new Promise((r) => setTimeout(r, 0)); } }, s);
const shot = async (n) => { await pump(0.4); await p.evaluate(() => window.QD.world.stage.step(1)); await p.screenshot({ path: `${out}/${n}.png` }); };
await p.evaluate((cls) => { const { S, E, showBoard } = window.QD; const h = E.newHero({ name: 'Dave', cls, seed: 5 }); h.level = 6; h.full = true; h.dice = null; S.hero = h; S.company = { members: [h] }; h.campaign.step = 4; showBoard(); }, cls);
await pump(1);
await p.evaluate(() => { const q = window.QD.E.questsFor(window.QD.S.hero)[0]; q.enemies = ['goblin', 'wolf']; window.QD.startQuest(q); });
for (let i = 0; i < 120; i++) { if (await p.evaluate(() => !!document.querySelector('#b3-roll'))) break; await pump(0.5); }
await pump(3); await p.evaluate(() => document.querySelector('#b3-roll')?.click()); await pump(9);
await p.evaluate(() => { window.QD.S.battle.magic = 8; window.QD.B3.renderShape(); }); await pump(0.5);
await p.evaluate(() => document.querySelector('.b3-powers')?.click()); await pump(0.5); await shot('1-sheet');
await p.evaluate(() => document.querySelector('.bcard')?.click()); await pump(0.5); await shot('2-detail');
console.log('before use magic', await p.evaluate(() => window.QD.S.battle.magic));
await p.evaluate(() => document.querySelector('.pd-sq[aria-label="One more magic"]')?.click()); await pump(0.3); await shot('3-stepped');
await p.evaluate(() => document.querySelector('.pd-btn.go')?.click()); await pump(1.2); await shot('4-used');
console.log('after use magic', await p.evaluate(() => window.QD.S.battle.magic), JSON.stringify(await p.evaluate(() => window.QD.S.battle.lastCast)));
console.log(problems.join('|') || 'no errors'); await b.close();
